[package]
name = "hypua"
version = "0.1.0"
authors = ["kiwiyou <kiwiyou.dev@gmail.com>"]
edition = "2018"
license = "Unlicense"

[dependencies]
phf = { version = "0.8.0", default-features = false }

[build-dependencies]
phf_codegen = "0.8.0"
